on:
  push:
    brnaches:
      - xdev-release

name: Deploy to Amazon ECS

jobs:
  tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ~/xserver
    container: circleci/python:3.7.5

    steps:
      - name: Setup file system permissions
        run: sudo chmod -R 777 $GITHUB_WORKSPACE /github /__w/_temp
      - name: checkout
        uses: actions/checkout@v2

      - name: Cache dependency
        uses: actions/cache@v2
        with:
          path: ./env
          key: deps-${{ hashFiles('**/requirements.txt') }}

      - name: install dependencies
        run: |
          python3 -m venv env
      #     . env/bin/activate
      #     pip install -r requirements.txt
      # - name: run tests
      #   run: |
      #     . env/bin/activate
      #     python manage.py test
